version: 0.2
phases:
  install:
    runtime-versions: 
      java: corretto11
    commands:
      - './gradlew wrapper --gradle-version 6.0.1'
  build:
    commands:
      - chmod +x ./gradlew
      - ./gradlew assembleDebug
artifacts:
  files:
     - './android/app/build/outputs/**/*.apk'
  discard-paths: yes
