version: 0.2
phases:
  install:
    runtime-versions: 
      java: corretto11
      #android: 28
   build:
    commands:
      - chmod +x ./gradlew
      - ./gradlew assembleDebug
      - echo "it is done"
artifacts:
  files:
     - './android/app/build/outputs/**/*.apk'
  discard-paths: yes
